name: mol-env
channels:
  - rdkit
  - anaconda
  - schrodinger
  - defaults
dependencies:
  - python=3.7.7
  - pip
  - rdkit
  - sphinx
  - flake8
  - pytest
  - pytest-cov
  - pymol
  - pymol-bundle
  - numpy
  - scipy
  - pip:
      - gym
      - rstcheck
      - hypothesis
      - pyfakefs
      - importlib-resources